### PR TITLE
Spanish language added

### PR DESCRIPTION
**Pull request by codexilab**
CHANGELOG:

* Added advcaptcha_plugin() in line 123
* Added spanish language

### CODE REVIEW

**Comment by webmods-croatia** [comment]
Thanks for the interest in the plugin. ;)

I will merge this soon and release the plugin on Market (1.0.0 is available on GitHub, but I need to finish the screenshots).

Do you want me to put your GitHub account link in changelog (e.g. "thanks to CodexiLab") and if yes which link? Also I should put it in es_ES .po file instead of my link.

**Comment by codexilab** [comment]
> Thanks for the interest in the plugin. ;)
> 
> I will merge this soon and release the plugin on Market (1.0.0 is available on GitHub, but I need to finish the screenshots and cover image).
> 
> Do you want me to put your GitHub account link in changelog (e.g. "thanks to CodexiLab") and if yes which link (@codexilab @AdrianOlmedo)?

@codexilab username is ok, ¡gracias! 

> Also I should put it in es_ES .po file instead of my link.

I had forgotten to edit the letterhead of the .po file

**Comment by codexilab** [comment]
> Did you add those line breaks between the rows or it's some bug?

I have not done it. It must be some github error that makes it show like this with "line breaks". Check the code with Raw.

**Comment by codexilab** [comment]
I have moved this https://github.com/webmods-croatia/oscplugin-advcaptcha/pull/1/commits/aec126e303a9b1c02e4c5b780489ac1a55826aa9 to another Pull request https://github.com/webmods-croatia/oscplugin-advcaptcha/pull/2 as a suggestion.

**Comment by webmods-croatia** [comment]
I will merge now and check the line breaks later at PC.

**Pull request merged**
